[package]
name = "nn-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
approx = "0.5.1"
rand = "0.9.0-alpha.2"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
plotters = "0.3.3"
